# Generated by Django 2.2.7 on 2020-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='primary_photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
