# Generated by Django 2.2.7 on 2020-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0002_billboard_primary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='rent',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
