# Generated by Django 2.2.7 on 2020-02-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0003_auto_20200205_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
