# Generated by Django 2.2.7 on 2020-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0004_auto_20200205_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
